name: deploy-to-npm-prerelease
on: workflow_dispatch
jobs:
  deploy-prerelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.10'
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SYNC_SSH_KEY_GITHUB_DEPLOY_TO_NPM }}
          known_hosts: ${{ secrets.SYNC_KNOWN_HOSTS_GITHUB }}
      - name: Save NPM auth details to .npmrc
        run: echo //registry.npmjs.org/:_authToken=$NPM_PUBLISH_KEY >> .npmrc
        env:
          NPM_PUBLISH_KEY: ${{ secrets.NPM_PUBLISH_KEY }}
      - run: npm whoami
      - run: git config --global user.email team@halfhelix.com
      - run: git config --global user.name Deployments
      - run: npm i -g lerna
      - run: lerna bootstrap
      - run: lerna publish prerelease --no-verify-access --yes
